#!/bin/bash -e

# 
# This script generates controllers, services and models.
#
# OPTIONS
# -c        Generates a controller.
# -m        Generates a model
# -r        Generates a router.
# -s        Generates a service.        
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
entryPoint="$SCRIPT_DIR/src/generate.ts"
controller=false
model=false
router=false
service=false
help=false
controllersPath="./controllers";
modelsPath="./models";
servicesPath="./services";
routersPath="./routes";

while getopts cmrsh flag
do
  case "${flag}" in
      c) controller=true;;
      m) model=true;;
      r) router=true;;
      s) service=true;;
      h) help=true;;
  esac
done

if "$help" || [ -z "$2" ] || [ $controller == "false" ] && [ $service == "false" ] && [ $model == "false" ] && [ $router == "false" ]; then
    echo ""
    echo "This script generates controllers, services, models and routers."
    echo "Pass an option and a name for the component."
    echo ""
    echo "OPTIONS: "
    echo "-c    Generates a controller."
    echo "-m    Generates a model."
    echo "-r    Generates a router."
    echo "-s    Generates a service."
    echo ""
    exit
fi

if "$controller" && [ ! -z "$2" ]; then
    deno run --allow-read --allow-write --no-check $entryPoint controller $2 $controllersPath
fi

if "$model" && [ ! -z "$2" ]; then
    deno run --allow-read  --allow-write --no-check $entryPoint model $2 $modelsPath
fi

if "$router" && [ ! -z "$2" ]; then
    deno run --allow-read  --allow-write --no-check $entryPoint router $2 $routersPath
fi

if "$service" && [ ! -z "$2" ]; then
    deno run --allow-read  --allow-write --no-check $entryPoint service $2 $servicesPath
fi