version: "3.9"
services:
  auth-postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRESQL_USERNAME: bn_keycloak
      POSTGRESQL_DATABASE: bitnami_keycloak
    volumes:
      - 'auth_postgresql_data:/bitnami/postgresql'
  auth-server:
    image: docker.io/bitnami/keycloak:15
    depends_on:
      - auth-postgresql
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN_USER: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KEYCLOAK_DATABASE_HOST: auth-postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: bitnami_keycloak
      KEYCLOAK_DATABASE_USER: bn_keycloak
      # KEYCLOAK_DATABASE_PASSWORD: password
  api-server:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - auth-server
    environment:
      PORT: 8000
      ENV: dev
      AUTH_HOST: auth-server:8080
      AUTH_CLIENT_ID: deno-sandbox
      AUTH_CLIENT_SECRET: 66809fe3-3235-475f-aff5-e8aba041308b
      AUTH_REALM: myrealm
      AUTH_SSL: "false"
volumes:
  auth_postgresql_data:
    driver: local
